### ISSUE TITLE
Map explorer layers in Myanmar site no longer displaying

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#865]
![image](https://cloud.githubusercontent.com/assets/14996905/15244259/8fd493a2-1900-11e6-90b1-a5d38df2969f.png)
Tried in Chrome and Firefox. 
When we tested adding a new layer today it displayed.

**Comment by Huyeng** [comment]
@prustar, does the issue fix?

**Comment by prustar** [comment]
@Huyeng I believe its just me and the Myanmar team. I checked now and still the layers don't show for me except for the test layer that was added. @yanoak @tnyoon @DragonVirus Do you guys still have the same issue or have the layers started to show up now? I'm using Chrome and Firefox, it's the same on both.

**Comment by rustedfish** [comment]
@prustar @Huyeng I deleted the map layer which we added together because Burmese fonts are not displaying. And uploaded new layers in Test Page but both languages are not displaying yet.

**Comment by DragonVirus** [comment]
it works in pp-myanmar site. Still doesn't work in production site. 
For the burmese fonts, i think we need to add font embedded to the site.

**Comment by Huyeng** [comment]
Which working layer that is testing. I noticed that the filling information of layers for dual sites that need to publish on the map explorer layer  are not correctly at all. I will create the wiki document for guideline.

**Comment by Huyeng** [comment]
Here is the brief guideline: https://wiki.opendevelopmentmekong.net/partners:map-explorer-page#layer_settings

**Comment by acorbi** [comment]
@Huyeng FYI: I have linked your guide from the homepage of the wiki https://wiki.opendevelopmentmekong.net/start

**Comment by Huyeng** [comment]
Added. Can I close this issue?

**Comment by prustar** [comment]
@Huyeng I still don't get any layers appearing except for the test layer: 

![image](https://cloud.githubusercontent.com/assets/14996905/15572847/8d361402-2343-11e6-9174-7bd1ce0bfc99.png)

**Comment by S-mardii** [comment]
I believe the issue happen when you switch from https://myanmar.pp.opendevelopmentmekong.net/map-explorer/ to https://myanmar.opendevelopmentmekong.net/my/map-explorer/

**Comment by S-mardii** [comment]
Therefore the solution for this is to add the missing info into: **Download URL (Burmese), CartoDB URL (Burmese)**  and  **Enter your HTML code to use as legend on the layer (Burmese)**.

**Comment by S-mardii** [comment]
![edit layer open development myanmar wordpress 2016-05-27 16-37-19](https://cloud.githubusercontent.com/assets/18528756/15604281/ad9d1d3a-2429-11e6-8016-5e56ea45be6f.png)

**Comment by S-mardii** [comment]
As Map Layers in Burmese font hasn't embedded, I would suggest you copy the URL of layers in English for the time being.

**Comment by S-mardii** [comment]
Here is the Example:
First you have this: 
![screenshot_1](https://cloud.githubusercontent.com/assets/18528756/15604578/591bcc00-242b-11e6-9997-20e7c59f06e3.png)
That is why the result is like this:
![screenshot_2](https://cloud.githubusercontent.com/assets/18528756/15604643/ae127cfe-242b-11e6-92e1-8ce62ccd75d0.png)

**Comment by S-mardii** [comment]
My suggested solution is to copy the values in the red boxes and paste it in the green boxes according to the number in this screenshot.
![edit layer open development myanmar wordpress 2016-05-27 16-58-59](https://cloud.githubusercontent.com/assets/18528756/15604826/7eace4bc-242c-11e6-8137-acaecc131125.png)
The result will be like this:
![screenshot_3](https://cloud.githubusercontent.com/assets/18528756/15604861/b3ed2146-242c-11e6-825a-c041eddbaea1.png)

**Comment by Huyeng** [comment]
Thanks @S-mardii for your suggestion and solution.  
The layers won't show in Burma page because of no data entry into, but on English page, they are. 
@prustar Please coordinates the Myanmar team to add the map layers for Burma page.

Moreover, we noticed that there is some problems with Myanmar language due to not embeding the font. Please recommend the fonts to due for the site then we can embed them.

**Comment by acorbi** [comment]
## yeah, thanks a lot for your detail report with screenshots. very helpful to understand both problem and solution!

Gesendet von der myMail-App für Android Freitag, 27 Mai 2016, 00:50nachm. +02:00 von Huyeng  notifications@github.com :

**Comment by prustar** [comment]
@Huyeng @S-mardii -- these layers were loaded before the changes to the WP was made to include the multi-lingual aspects were included. I believe @tnyoon has been working with @acorbi to finalise these - please correct me if I'm wrong. I have provided the training on how to localise the map explorer in wordpress, CKAN and CartoDB so once the language embedding has been finalise they can commence this process.

**Comment by prustar** [comment]
Just noticed on the Vietnamese site that there's a box for language selection which was present in the Cambodia site as well but no longer there and is missing in the Myanmar site. Is this box significant? 

![image](https://cloud.githubusercontent.com/assets/14996905/15610887/f0ebe316-2427-11e6-93bf-f19b3b26626e.png)

**Comment by Huyeng** [comment]
The language selection is not available for Vietnam. It was come with migration, and ODC continues to use it to filter posts that belong to the language only. 

@prustar  can the issue close?

**Comment by acorbi** [comment]
@prustar @Huyeng can we close this Issue? Did it get solved with configuration or with the latest improvements on Map explorer?

**Comment by prustar** [comment]
@acorbi Left it running for 5 whole minutes and nothing in either Chrome or Firefox. The test layer is the only one that displays. Also the info windows still not displaying. Love the spinning wheel tells me that when I selected the layer something was at least triggered. 

![image](https://cloud.githubusercontent.com/assets/14996905/15936431/506e0d08-2e6b-11e6-8117-16e089c6adb7.png)

**Comment by acorbi** [comment]
@prustar  @huyeng @jpeizer please try refreshing the burmese map explorer via CTRL+F5 (windows) or CMD+R (osx) or browsing it in incognito mode, clearing the cache or using a broser you have not used before... do the maps now appear?

**Comment by prustar** [comment]
@Huyeng @S-mardii @acorbi -- All working now. Closing.
